kind: Service
apiVersion: v1
metadata:
  name: miro-icon-drag-drop-service
spec:
  selector:
    app: miro-icon-drag-drop-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miro-icon-drag-drop
  labels:
    app: miro-icon-drag-drop-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miro-icon-drag-drop-service
  template:
    metadata:
      labels:
        app: miro-icon-drag-drop-service
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: miro-icon-drag-drop-service
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80